spring.application.name=stayease

#DB CONFIGURATION

spring.datasource.url = jdbc:postgresql://localhost:5432/stayease_db
spring.datasource.username = stayease_role
spring.datasource.password = 2005@18
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql=true

